apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: epp-routing
  namespace: default
spec:
  parentRefs:
  - name: inference-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /preproc
    backendRefs:
    - name: envoy-shim
      port: 80
