name: Copyright Checks

on:
  pull_request

# Cancel any previous check runs for the same pull request to avoid redundant workflows.
concurrency:
  group: ${{ github.event_name == 'pull_request' && format('{0}-{1}', github.workflow, github.event.pull_request.number) || '' }}
  cancel-in-progress: true

jobs:
  copyright-checks:
      runs-on: ubuntu-24.04
      container:
        image: ghcr.io/${{ github.repository }}/helm-tester:0.1.1
        options: --tty
        volumes:
        - ${{ github.workspace }}:/workspace
      permissions:
        contents: read
        packages: read
      steps:
      - uses: actions/checkout@v4
        # Allowlist both variants of the mounted source directory.
      - run: git config --global --add safe.directory /__w/dynamo/dynamo
      - run: git config --global --add safe.directory /workspace
      - run: pwsh /workspace/.github/workflows/copyright-check.ps1
        env:
          NVBUILD_VERBOSITY: DETAILED
        timeout-minutes: 2
        working-directory: /workspace
